update ImageFiles set ImageContent = 3, FeaturedPull='Arc (AR)' where Name='A0449'
update ImageFiles set ImageContent = 3, FeaturedPull='Bevel (BL)' where Name='A0450'
update ImageFiles set ImageContent = 3, FeaturedPull='Classic (CL)' where Name='A0453'
update ImageFiles set ImageContent = 3, FeaturedPull='Traditional (TD)' where Name='A0457'
update ImageFiles set ImageContent = 3, FeaturedPull='Premier (PE)' where Name='A0455'
update ImageFiles set ImageContent = 3, FeaturedPull='Traditional Knob (TK)' where Name='A0459'
update ImageFiles set ImageContent = 3, FeaturedPull='Chamfer (CH)' where Name='A0465'
update ImageFiles set ImageContent = 3, FeaturedPull='Rod (RD)' where Name='A0469'
update ImageFiles set ImageContent = 3, FeaturedPull='Shark (SH)' where Name='A0473'
update ImageFiles set ImageContent = 3, FeaturedPull='Keyhole (KH)' where Name='A0480'
update ImageFiles set ImageContent = 3, FeaturedPull='Rainbow (RB)' where Name='A0481'
update ImageFiles set ImageContent = 3, FeaturedPull='Waterfall (WF)' where Name='A0482'
update ImageFiles set ImageContent = 3, FeaturedPull='Bead (BD)' where Name='A0438'
update ImageFiles set ImageContent = 3, FeaturedPull='Cable (CB)' where Name='A0440'
update ImageFiles set ImageContent = 3, FeaturedPull='Slot (ST)' where Name='A0492'
update ImageFiles set ImageContent = 3, FeaturedPull='Wave (WV)' where Name='A0493'
update ImageFiles set ImageContent = 3, FeaturedPull='Ramp (RP)' where Name='A0443'
update ImageFiles set ImageContent = 3, FeaturedPull='Spline (SP)' where Name='A0441'
update ImageFiles set ImageContent = 3, FeaturedPull='Sweep (SW)' where Name='A0442'
update ImageFiles set ImageContent = 3, FeaturedPull='Beam (BM)' where Name='A0439'
update ImageFiles set ImageContent = 3, FeaturedPull='Arc (AC)' where Name='A0791'
update ImageFiles set ImageContent = 3, FeaturedPull='Bar (BR)' where Name='A0789'
update ImageFiles set ImageContent = 3, FeaturedPull='Crescent (CS)' where Name='A0790'
update ImageFiles set ImageContent = 3, FeaturedPull='Axis (AS)' where Name='A0786'
update ImageFiles set ImageContent = 3, FeaturedPull='Radius (RS)' where Name='A0787'
update ImageFiles set ImageContent = 3, FeaturedPull='Wing (WG)' where Name='A0788'
update ImageFiles set ImageContent = 3, FeaturedPull='Prominence Pull' where Name='A0487'
go
update ImageFiles set ImageContent = 2, FeaturedEdge='I-Beam (IB)' where Name='A0445'
update ImageFiles set ImageContent = 2, FeaturedEdge='Ridge (RG)' where Name='A0446'
update ImageFiles set ImageContent = 2, FeaturedEdge='Ridge (RG)' where Name='A0446'
update ImageFiles set ImageContent = 2, FeaturedEdge='PVC Soft (PS)' where Name='A0447'
update ImageFiles set ImageContent = 2, FeaturedEdge='Soft (SO)' where Name='A0447'
update ImageFiles set ImageContent = 2, FeaturedEdge='Soft (SO)' where Name='A0447'
update ImageFiles set ImageContent = 2, FeaturedEdge='Softenend (SF)' where Name='A0447'
update ImageFiles set ImageContent = 2, FeaturedEdge='Altamont Edge' where Name='A0452'
update ImageFiles set ImageContent = 2, FeaturedEdge='Coronado (CE)' where Name='A0461'
update ImageFiles set ImageContent = 2, FeaturedEdge='Knife (KF)' where Name='A0474'
update ImageFiles set ImageContent = 2, FeaturedEdge='Shark (SH)' where Name='A0476'
update ImageFiles set ImageContent = 2, FeaturedEdge='Angle (AG)' where Name='A0478'
update ImageFiles set ImageContent = 2, FeaturedEdge='Kerf (KF)' where Name='A0479'
update ImageFiles set ImageContent = 2, FeaturedEdge='Chamfer (CF)' where Name='A0483'
update ImageFiles set ImageContent = 2, FeaturedEdge='Quarter Bullnose (QB)' where Name='A0484'
update ImageFiles set ImageContent = 2, FeaturedEdge='Cove (CV)' where Name='A0494'
update ImageFiles set ImageContent = 2, FeaturedEdge='Crescent (CS)' where Name='A0495'
update ImageFiles set ImageContent = 2, FeaturedEdge='Double Bead (DB)' where Name='A0496'
update ImageFiles set ImageContent = 2, FeaturedEdge='Reeded (RD)' where Name='A0497'
update ImageFiles set ImageContent = 2, FeaturedEdge='Butterfly (BF)' where Name='A0635'
update ImageFiles set ImageContent = 2, FeaturedEdge='Reflect (RE)' where Name='A0636'
go
update ImageFiles set ImageContent = 4, FeaturedFinish='White (LWH)', FinishType=2, FinishSubType=4 where Name='A0753'
update ImageFiles set ImageContent = 4, FeaturedFinish='Shaker Cherry (LKC)', FinishType=2, FinishSubType=5 where Name='A0754'
update ImageFiles set ImageContent = 4, FeaturedFinish='Platinum (LPN)', FinishType=2, FinishSubType=4 where Name='A0755'
update ImageFiles set ImageContent = 4, FeaturedFinish='Natural Maple (LNM)', FinishType=2, FinishSubType=5 where Name='A0756'
update ImageFiles set ImageContent = 4, FeaturedFinish='Light Cherry (LLC)', FinishType=2, FinishSubType=5 where Name='A0757'
update ImageFiles set ImageContent = 4, FeaturedFinish='Java Cherry (LJC)', FinishType=2, FinishSubType=5 where Name='A0758'
update ImageFiles set ImageContent = 4, FeaturedFinish='Huntington Maple (LUM)', FinishType=2, FinishSubType=5 where Name='A0759'
update ImageFiles set ImageContent = 4, FeaturedFinish='Harvest Maple (LVM)', FinishType=2, FinishSubType=5 where Name='A0760'
update ImageFiles set ImageContent = 4, FeaturedFinish='Harbor Teak (LHT)', FinishType=2, FinishSubType=5 where Name='A0761'
update ImageFiles set ImageContent = 4, FeaturedFinish='Golden Cherry (LGC)', FinishType=2, FinishSubType=5 where Name='A0762'
update ImageFiles set ImageContent = 4, FeaturedFinish='Empire Walnut (LEW)', FinishType=2, FinishSubType=5 where Name='A0763'
update ImageFiles set ImageContent = 4, FeaturedFinish='Cordovan Cherry (LCC)', FinishType=2, FinishSubType=5 where Name='A0764'
update ImageFiles set ImageContent = 4, FeaturedFinish='Columbian Walnut (LCW)', FinishType=2, FinishSubType=5 where Name='A0765'
update ImageFiles set ImageContent = 4, FeaturedFinish='Clear Maple (LCM)', FinishType=2, FinishSubType=5 where Name='A0766'
update ImageFiles set ImageContent = 4, FeaturedFinish='Brighton Walnut (LBW)', FinishType=2, FinishSubType=5 where Name='A0767'
update ImageFiles set ImageContent = 4, FeaturedFinish='Traditional Walnut (VTW)', FinishType=1, FinishSubType=3 where Name='A0768'
update ImageFiles set ImageContent = 4, FeaturedFinish='Empire Walnut (VEW)', FinishType=1, FinishSubType=3 where Name='A0769'
update ImageFiles set ImageContent = 4, FeaturedFinish='Columbian Walnut (VCW)', FinishType=1, FinishSubType=3 where Name='A0770'
update ImageFiles set ImageContent = 4, FeaturedFinish='Brighton Walnut (VBW)', FinishType=1, FinishSubType=3 where Name='A0771'
update ImageFiles set ImageContent = 4, FeaturedFinish='American Walnut (VAW)', FinishType=1, FinishSubType=3 where Name='A0772'
update ImageFiles set ImageContent = 4, FeaturedFinish='Natural Maple (VNM)', FinishType=1, FinishSubType=2 where Name='A0773'
update ImageFiles set ImageContent = 4, FeaturedFinish='Huntington Maple (VUM)', FinishType=1, FinishSubType=2 where Name='A0774'
update ImageFiles set ImageContent = 4, FeaturedFinish='Harvest Maple (VVM)', FinishType=1, FinishSubType=2 where Name='A0775'
update ImageFiles set ImageContent = 4, FeaturedFinish='Golden Maple (VGM)', FinishType=1, FinishSubType=2 where Name='A0776'
update ImageFiles set ImageContent = 4, FeaturedFinish='Clear Maple (VCM)', FinishType=1, FinishSubType=2 where Name='A0777'
update ImageFiles set ImageContent = 4, FeaturedFinish='Traditional Cherry (VTC)', FinishType=1, FinishSubType=1 where Name='A0778'
update ImageFiles set ImageContent = 4, FeaturedFinish='Shaker Cherry (VKC)', FinishType=1, FinishSubType=1 where Name='A0779'
update ImageFiles set ImageContent = 4, FeaturedFinish='Natural Cherry (VNC)', FinishType=1, FinishSubType=1 where Name='A0780'
update ImageFiles set ImageContent = 4, FeaturedFinish='Mahogany Cherry (VHC)', FinishType=1, FinishSubType=1 where Name='A0781'
update ImageFiles set ImageContent = 4, FeaturedFinish='Light Cherry (VLC)', FinishType=1, FinishSubType=1 where Name='A0782'
update ImageFiles set ImageContent = 4, FeaturedFinish='Java Cherry (VJC)', FinishType=1, FinishSubType=1 where Name='A0783'
update ImageFiles set ImageContent = 4, FeaturedFinish='Golden Cherry (VGC)', FinishType=1, FinishSubType=1 where Name='A0784'
update ImageFiles set ImageContent = 4, FeaturedFinish='Cordovan Cherry (VCC)', FinishType=1, FinishSubType=1 where Name='A0785'
update ImageFiles set ImageContent = 4, FeaturedFinish='Monterey Beige Laminate (LMB)', FinishType=2, FinishSubType=6 where Name='A0792'
update ImageFiles set ImageContent = 4, FeaturedFinish='Desert Zephyr Laminate (LDZ)', FinishType=2, FinishSubType=6 where Name='A0793'
update ImageFiles set ImageContent = 4, FeaturedFinish='Canyon Zephyr Laminate (LCZ)', FinishType=2, FinishSubType=6 where Name='A0794'
update ImageFiles set ImageContent = 4, FeaturedFinish='Twilight Zephyr Laminate (LTZ)', FinishType=2, FinishSubType=6 where Name='A0795'
update ImageFiles set ImageContent = 4, FeaturedFinish='Sheer Mesh Laminate (LSH)', FinishType=2, FinishSubType=6 where Name='A0796'
update ImageFiles set ImageContent = 4, FeaturedFinish='Steel Mesh Laminate (LST)', FinishType=2, FinishSubType=6 where Name='A0797'
update ImageFiles set ImageContent = 4, FeaturedFinish='Charcoal Laminate (LCR)', FinishType=2, FinishSubType=4 where Name='A0798'
update ImageFiles set ImageContent = 4, FeaturedFinish='Gray Cloud Laminate (LYC)', FinishType=2, FinishSubType=4 where Name='A0800'
go