//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace PDWDBContext
{
    public partial class Attribute
    {
        public Attribute()
        {
            this.AttributeOptions = new HashSet<AttributeOption>();
            this.SeriesIntAttributes = new HashSet<SeriesIntAttribute>();
            this.SeriesOptionAttributes = new HashSet<SeriesOptionAttribute>();
            this.SeriesTextAttributes = new HashSet<SeriesTextAttribute>();
        }
    
        public int AttributeID { get; set; }
        public string Name { get; set; }
        public bool DetailItem { get; set; }
    
        public virtual ICollection<AttributeOption> AttributeOptions { get; set; }
        public virtual ICollection<SeriesIntAttribute> SeriesIntAttributes { get; set; }
        public virtual ICollection<SeriesOptionAttribute> SeriesOptionAttributes { get; set; }
        public virtual ICollection<SeriesTextAttribute> SeriesTextAttributes { get; set; }
    }
    
}
