//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace PDWDBContext
{
    public partial class CollateralOrder
    {
        public CollateralOrder()
        {
            this.CollateralOrderDetails = new HashSet<CollateralOrderDetail>();
            this.CollateralOrderShipments = new HashSet<CollateralOrderShipment>();
        }
    
        public int OrderID { get; set; }
        public int RequestingParty { get; set; }
        public Nullable<int> PaoliRepGroupID { get; set; }
        public Nullable<int> DealerID { get; set; }
        public string EndUserFirstName { get; set; }
        public string EndUserLastName { get; set; }
        public string EndUserPhoneNumber { get; set; }
        public string EndUserEMailAddress { get; set; }
        public int ShippingType { get; set; }
        public string ShippingFedexAccount { get; set; }
        public string ShippingCompanyName { get; set; }
        public string ShippingAddress1 { get; set; }
        public string ShippingAddress2 { get; set; }
        public string ShippingCity { get; set; }
        public string ShippingState { get; set; }
        public string ShippingZip { get; set; }
        public string ShippingPhoneNumber { get; set; }
        public string ShippingEmailAddress { get; set; }
        public System.DateTime OrderDate { get; set; }
        public Nullable<int> PaoliRepGroupMemberID { get; set; }
        public Nullable<int> DealerMemberID { get; set; }
        public int ShippingAddressType { get; set; }
        public Nullable<int> PaoliMemberID { get; set; }
        public int Status { get; set; }
        public string ShippingAttn { get; set; }
        public int CreatedByUserID { get; set; }
        public Nullable<int> CanceledByUserID { get; set; }
        public Nullable<System.DateTime> CanceledOnDateTime { get; set; }
        public int ShippingParty { get; set; }
        public Nullable<int> SPPaoliMemberID { get; set; }
        public Nullable<int> SPPaoliRepGroupID { get; set; }
        public Nullable<int> SPPaoliRepGroupMemberID { get; set; }
        public Nullable<int> SPDealerID { get; set; }
        public Nullable<int> SPDealerMemberID { get; set; }
        public string SPEndUserFirstName { get; set; }
        public string SPEndUserLastName { get; set; }
        public string SPEndUserPhoneNumber { get; set; }
        public string SPEndUserEMailAddress { get; set; }
        public string RequestingPartyName { get; set; }
        public string ShippingPartyName { get; set; }
    
        public virtual ICollection<CollateralOrderDetail> CollateralOrderDetails { get; set; }
        public virtual Company Dealer { get; set; }
        public virtual Company PaoliSalesRep { get; set; }
        public virtual User DealerMember { get; set; }
        public virtual User PaoliSalesRepMember { get; set; }
        public virtual User PaoliMember { get; set; }
        public virtual User CreatedByUser { get; set; }
        public virtual ICollection<CollateralOrderShipment> CollateralOrderShipments { get; set; }
        public virtual User CanceledByUser { get; set; }
        public virtual Company SPDealer { get; set; }
        public virtual User SPDealerMember { get; set; }
        public virtual User SPPaoliMember { get; set; }
        public virtual Company SPPaoliSalesRep { get; set; }
        public virtual User SPPaoliSalesRepMember { get; set; }
    }
    
}
