//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace PDWDBContext
{
    public partial class CollateralGroupItem
    {
        public int GroupID { get; set; }
        public int CollateralID { get; set; }
        public int Quantity { get; set; }
    
        public virtual CollateralItem ChildCollateralItem { get; set; }
        public virtual CollateralItem GroupCollateralItem { get; set; }
    }
    
}
