//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace PDWDBContext
{
    public partial class CollateralOrderShipmentDetail
    {
        public int DetailID { get; set; }
        public int ShipmentID { get; set; }
        public int OrderDetailID { get; set; }
        public int Quantity { get; set; }
    
        public virtual CollateralOrderDetail CollateralOrderDetail { get; set; }
        public virtual CollateralOrderShipment CollateralOrderShipment { get; set; }
    }
    
}
