//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace PDWDBContext
{
    public partial class CollateralOrderShipment
    {
        public CollateralOrderShipment()
        {
            this.CollateralOrderShipmentDetails = new HashSet<CollateralOrderShipmentDetail>();
        }
    
        public int ShipmentID { get; set; }
        public int OrderID { get; set; }
        public string Vendor { get; set; }
        public string GLCode { get; set; }
        public string ShippingType { get; set; }
        public string ShippingFedexAccount { get; set; }
        public string ShippingAttn { get; set; }
        public string ShippingCompanyName { get; set; }
        public string ShippingAddress1 { get; set; }
        public string ShippingAddress2 { get; set; }
        public string ShippingCity { get; set; }
        public string ShippingState { get; set; }
        public string ShippingZip { get; set; }
        public string ShippingPhoneNumber { get; set; }
        public string ShippingEmailAddress { get; set; }
        public System.DateTime ShipmentDate { get; set; }
        public string TrackingNumber1 { get; set; }
        public string TrackingNumber2 { get; set; }
        public string TrackingNumber3 { get; set; }
        public string TrackingNumber4 { get; set; }
    
        public virtual CollateralOrder CollateralOrder { get; set; }
        public virtual ICollection<CollateralOrderShipmentDetail> CollateralOrderShipmentDetails { get; set; }
    }
    
}
