//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace PDWDBContext
{
    public partial class CollateralItem
    {
        public CollateralItem()
        {
            this.CollateralGroups = new HashSet<CollateralGroupItem>();
            this.CollateralGroupItems = new HashSet<CollateralGroupItem>();
        }
    
        public int CollateralID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string LeadTime { get; set; }
        public Nullable<System.DateTime> StatusDate { get; set; }
        public int Quantity { get; set; }
        public string ImageFileName { get; set; }
        public Nullable<double> Price { get; set; }
        public Nullable<double> Shipping { get; set; }
        public Nullable<double> Weight { get; set; }
        public bool IsGroup { get; set; }
        public Nullable<int> CollateralTypeID { get; set; }
        public bool IsActive { get; set; }
    
        public virtual CollateralType CollateralType { get; set; }
        public virtual ICollection<CollateralGroupItem> CollateralGroups { get; set; }
        public virtual ICollection<CollateralGroupItem> CollateralGroupItems { get; set; }
    }
    
}
