//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace PDWDBContext
{
    public partial class CompanyTripData
    {
        public int CompanyID { get; set; }
        public Nullable<decimal> TotalSalesYTD { get; set; }
        public Nullable<int> TotalTripsYTD { get; set; }
        public Nullable<decimal> SalesToNextTrip { get; set; }
        public Nullable<decimal> ShakaThreshold { get; set; }
        public Nullable<decimal> ShakaPercentGrowthYTD { get; set; }
        public Nullable<int> ShakaPercentGrowthRank { get; set; }
        public Nullable<decimal> ShakaDollarGrowthYTD { get; set; }
        public Nullable<int> ShakaDollarGrowthRank { get; set; }
        public Nullable<decimal> AlohaThreshold { get; set; }
        public Nullable<decimal> AlohaPercentGrowthYTD { get; set; }
        public Nullable<int> AlohaPercentGrowthRank { get; set; }
        public Nullable<decimal> AlohaDollarGrowthYTD { get; set; }
        public Nullable<int> AlohaDollarGrowthRank { get; set; }
        public Nullable<decimal> MahaloThreshold { get; set; }
        public Nullable<decimal> MahaloPercentGrowthYTD { get; set; }
        public Nullable<int> MahaloPercentGrowthRank { get; set; }
        public Nullable<decimal> MahaloDollarGrowthYTD { get; set; }
        public Nullable<int> MahaloDollarGrowthRank { get; set; }
        public System.DateTime ImportDate { get; set; }
    
        public virtual Company Company { get; set; }
    }
    
}
