//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace PDWDBContext
{
    public partial class Company
    {
        public Company()
        {
            this.SpecRequests = new HashSet<SpecRequest>();
            this.SpecRequests1 = new HashSet<SpecRequest>();
            this.Users = new HashSet<User>();
            this.ShowroomImages = new HashSet<ImageFile>();
            this.CollateralOrders = new HashSet<CollateralOrder>();
            this.CollateralOrders1 = new HashSet<CollateralOrder>();
            this.CollateralOrders2 = new HashSet<CollateralOrder>();
            this.CollateralOrders3 = new HashSet<CollateralOrder>();
            this.eCollateralItems = new HashSet<eCollateralItem>();
            this.Projects = new HashSet<Project>();
            this.Projects1 = new HashSet<Project>();
        }
    
        public int CompanyID { get; set; }
        public string Name { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Zip { get; set; }
        public string Phone { get; set; }
        public string FAX { get; set; }
        public string MasterID { get; set; }
        public string SubCompanyIDs { get; set; }
        public int CompanyType { get; set; }
        public Nullable<int> TerritoryID { get; set; }
        public string PublicAddress1 { get; set; }
        public string PublicAddress2 { get; set; }
        public string PublicCity { get; set; }
        public string PublicState { get; set; }
        public string PublicZip { get; set; }
        public string PublicPhone { get; set; }
        public string PublicFAX { get; set; }
        public string ContactEmail { get; set; }
        public string WebSite { get; set; }
        public string PublicContactEmail { get; set; }
        public string PublicWebSite { get; set; }
        public string PublicDisplayName { get; set; }
        public string BusinessUnitName { get; set; }
        public Nullable<int> PaoliMemberID { get; set; }
        public Nullable<int> PaoliSalesRepMemberID { get; set; }
        public bool SignedUpForTrip { get; set; }
        public string TripGroup { get; set; }
        public string TierGroup { get; set; }
        public string ImageFileName { get; set; }
    
        public virtual ICollection<SpecRequest> SpecRequests { get; set; }
        public virtual ICollection<SpecRequest> SpecRequests1 { get; set; }
        public virtual ICollection<User> Users { get; set; }
        public virtual Territory Territory { get; set; }
        public virtual Showroom Showroom { get; set; }
        public virtual ICollection<ImageFile> ShowroomImages { get; set; }
        public virtual ICollection<CollateralOrder> CollateralOrders { get; set; }
        public virtual ICollection<CollateralOrder> CollateralOrders1 { get; set; }
        public virtual ICollection<CollateralOrder> CollateralOrders2 { get; set; }
        public virtual ICollection<CollateralOrder> CollateralOrders3 { get; set; }
        public virtual User PaoliMember { get; set; }
        public virtual User PaoliSalesRepMember { get; set; }
        public virtual ICollection<eCollateralItem> eCollateralItems { get; set; }
        public virtual ICollection<Project> Projects { get; set; }
        public virtual ICollection<Project> Projects1 { get; set; }
        public virtual CompanyTripData CompanyTripData { get; set; }
        public virtual TerritoryTripData TerritoryTripData { get; set; }
    }
    
}
