//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace PDWDBContext
{
    public partial class eCollateralSection
    {
        public int SectionID { get; set; }
        public int ItemID { get; set; }
        public Nullable<int> ImageID { get; set; }
        public string Content { get; set; }
        public int Sequence { get; set; }
    
        public virtual eCollateralItem eCollateralItem { get; set; }
        public virtual ImageFile ImageFile { get; set; }
    }
    
}
