//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace PDWDBContext
{
    public partial class eCollateralItem
    {
        public eCollateralItem()
        {
            this.eCollateralSections = new HashSet<eCollateralSection>();
        }
    
        public int ItemID { get; set; }
        public int CreatedByUserID { get; set; }
        public System.DateTime CreatedByDateTime { get; set; }
        public int LastModifiedByUserID { get; set; }
        public System.DateTime LastModifiedByDateTime { get; set; }
        public bool IsTemplate { get; set; }
        public string FileName { get; set; }
        public string URLText { get; set; }
        public Nullable<int> DealershipID { get; set; }
        public Nullable<int> DealershipPOCID { get; set; }
        public Nullable<int> LayoutID { get; set; }
        public int Status { get; set; }
        public Nullable<int> ContentType { get; set; }
        public bool IncludeDealerImage { get; set; }
        public Nullable<int> ProjectID { get; set; }
        public string OldProjectName { get; set; }
        public string OldEndCustomer { get; set; }
        public string OldDealershipPOCName { get; set; }
        public string OldDealershipPOCEmail { get; set; }
        public string OldDealershipPOCPhone { get; set; }
        public Nullable<int> OldDealershipPOCAcctType { get; set; }
    
        public virtual Company Company { get; set; }
        public virtual User CreatedByUser { get; set; }
        public virtual User DealershipPOC { get; set; }
        public virtual User ModifiedByUser { get; set; }
        public virtual ICollection<eCollateralSection> eCollateralSections { get; set; }
        public virtual Project Project { get; set; }
    }
    
}
