//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace PDWDBContext
{
    public partial class ImageFileSeries
    {
        public int AssociationID { get; set; }
        public bool IsFeatured { get; set; }
        public int ImageID { get; set; }
        public int SeriesID { get; set; }
    
        public virtual ImageFile ImageFile { get; set; }
        public virtual Series Series { get; set; }
    }
    
}
