//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace PDWDBContext
{
    public partial class LeadTimeDetail
    {
        public int LeadTimeID { get; set; }
        public string Headline { get; set; }
        public string PromoText { get; set; }
        public Nullable<int> UserID { get; set; }
        public string LeftSide { get; set; }
        public string RightSide { get; set; }
    
        public virtual User User { get; set; }
    }
    
}
