//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace PDWDBContext
{
    public partial class PageLink
    {
        public PageLink()
        {
            this.Dealers = new HashSet<Dealer>();
        }
    
        public int PageID { get; set; }
        public string Display { get; set; }
        public string URLLocation { get; set; }
    
        public virtual ICollection<Dealer> Dealers { get; set; }
    }
    
}
