//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace PDWDBContext
{
    public partial class Project
    {
        public Project()
        {
            this.SpecRequests = new HashSet<SpecRequest>();
            this.eCollateralItems = new HashSet<eCollateralItem>();
        }
    
        public int ProjectID { get; set; }
        public string ProjectName { get; set; }
        public Nullable<int> DealerID { get; set; }
        public string EndCustomer { get; set; }
        public Nullable<bool> IsGSA { get; set; }
        public Nullable<int> ContractID { get; set; }
        public bool HasADFirm { get; set; }
        public string ADFirm { get; set; }
        public Nullable<System.DateTime> AnticipatedOrderDate { get; set; }
        public Nullable<System.DateTime> AnticipatedShipDate { get; set; }
        public string VeneerCasegoods { get; set; }
        public Nullable<double> NetVeneerCasegoods { get; set; }
        public string LaminateCasegoods { get; set; }
        public Nullable<double> NetLaminateCasegoods { get; set; }
        public string Conferencing { get; set; }
        public Nullable<double> NetConferencing { get; set; }
        public string Seating { get; set; }
        public Nullable<double> NetSeating { get; set; }
        public bool SPADone { get; set; }
        public Nullable<int> Probability { get; set; }
        public string PrimaryCompetitor { get; set; }
        public string Comments { get; set; }
        public int PipelineStatus { get; set; }
        public int ProjectSuccess { get; set; }
    
        public virtual Company Company { get; set; }
        public virtual GSAContract GSAContract { get; set; }
        public virtual ICollection<SpecRequest> SpecRequests { get; set; }
        public virtual ICollection<eCollateralItem> eCollateralItems { get; set; }
    }
    
}
