//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace PDWDBContext
{
    public partial class ScoopArticle
    {
        public int ArticleID { get; set; }
        public string BigHeadline { get; set; }
        public string BigText { get; set; }
        public string BigImageURL { get; set; }
        public string SmallHeadline { get; set; }
        public string SmallText { get; set; }
        public string SmallImageURL { get; set; }
        public string ContentBlock { get; set; }
        public string Title { get; set; }
        public Nullable<System.DateTime> PubDate { get; set; }
        public int AuthorID { get; set; }
        public int Rank { get; set; }
        public bool ShowBigImage { get; set; }
        public int ArticleType { get; set; }
    
        public virtual User User { get; set; }
    }
    
}
