//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace PDWDBContext
{
    public partial class SearchResultsLog
    {
        public int LogID { get; set; }
        public System.DateTime SearchDateTime { get; set; }
        public string SearchTerm { get; set; }
        public int SeriesCount { get; set; }
        public int ImageCount { get; set; }
        public int TypicalCount { get; set; }
        public int PageCount { get; set; }
    }
    
}
