//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace PDWDBContext
{
    public partial class Series
    {
        public Series()
        {
            this.SeriesIntAttributes = new HashSet<SeriesIntAttribute>();
            this.SeriesOptionAttributes = new HashSet<SeriesOptionAttribute>();
            this.SeriesTextAttributes = new HashSet<SeriesTextAttribute>();
            this.SeriesImageFiles = new HashSet<SeriesImageFile>();
            this.ParentSerieses = new HashSet<Series>();
            this.ChildSerieses = new HashSet<Series>();
            this.SeriesTypicals = new HashSet<SeriesTypical>();
            this.ImageFileSerieses = new HashSet<ImageFileSeries>();
        }
    
        public int SeriesID { get; set; }
        public string Name { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int CategoryID { get; set; }
        public string DBKeywords { get; set; }
        public bool IsActive { get; set; }
    
        public virtual ICollection<SeriesIntAttribute> SeriesIntAttributes { get; set; }
        public virtual ICollection<SeriesOptionAttribute> SeriesOptionAttributes { get; set; }
        public virtual ICollection<SeriesTextAttribute> SeriesTextAttributes { get; set; }
        public virtual Category Category { get; set; }
        public virtual ICollection<SeriesImageFile> SeriesImageFiles { get; set; }
        public virtual ICollection<Series> ParentSerieses { get; set; }
        public virtual ICollection<Series> ChildSerieses { get; set; }
        public virtual ICollection<SeriesTypical> SeriesTypicals { get; set; }
        public virtual ICollection<ImageFileSeries> ImageFileSerieses { get; set; }
    }
    
}
