//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace PDWDBContext
{
    public partial class SpecRequestFile
    {
        public int FileID { get; set; }
        public int RequestID { get; set; }
        public string Extension { get; set; }
        public string Name { get; set; }
        public int VersionNumber { get; set; }
        public System.DateTime UploadDate { get; set; }
        public bool IsSpecTeam { get; set; }
    
        public virtual SpecRequest SpecRequest { get; set; }
    }
    
}
