//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace PDWDBContext
{
    public partial class SpecRequestEvent
    {
        public int EventID { get; set; }
        public int RequestID { get; set; }
        public int UserID { get; set; }
        public System.DateTime EventDate { get; set; }
        public int EventType { get; set; }
    
        public virtual SpecRequest SpecRequest { get; set; }
        public virtual User User { get; set; }
    }
    
}
