//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace PDWDBContext
{
    public partial class SpecRequest
    {
        public SpecRequest()
        {
            this.SpecRequestFiles = new HashSet<SpecRequestFile>();
            this.Typicals = new HashSet<Typical>();
            this.SpecRequestEvents = new HashSet<SpecRequestEvent>();
        }
    
        public int RequestID { get; set; }
        public string Name { get; set; }
        public Nullable<int> PaoliSalesRepGroupID { get; set; }
        public Nullable<int> PrimaryCompanyID { get; set; }
        public Nullable<int> DealerSalesRepID { get; set; }
        public Nullable<int> PaoliSpecTeamMemberID { get; set; }
        public string SavedLocation { get; set; }
        public Nullable<int> ListPrice { get; set; }
        public string FeaturedSeries { get; set; }
        public string SeriesList { get; set; }
        public Nullable<bool> Received { get; set; }
        public string SPLQuote { get; set; }
        public Nullable<System.DateTime> LastModifiedDate { get; set; }
        public string Material { get; set; }
        public string Finish { get; set; }
        public Nullable<bool> IsGoodForWeb { get; set; }
        public Nullable<bool> AvailableForIn2 { get; set; }
        public string Footprint { get; set; }
        public string Notes { get; set; }
        public bool IsCompleted { get; set; }
        public Nullable<int> PaoliSalesRepMemberID { get; set; }
        public string ProjectSize { get; set; }
        public bool NeedFloorplanSpecs { get; set; }
        public bool Need3DDrawing { get; set; }
        public bool NeedValueEng { get; set; }
        public bool NeedPhotoRendering { get; set; }
        public bool Need2DDrawing { get; set; }
        public bool NeedAuditSpecs { get; set; }
        public string Casegoods { get; set; }
        public string Conferencing { get; set; }
        public string Seating { get; set; }
        public string Finishes { get; set; }
        public bool Grommets { get; set; }
        public string GrommetDetails { get; set; }
        public string DrawerOption { get; set; }
        public string FabricGrade { get; set; }
        public string FabricDetails { get; set; }
        public string SpecialRequests { get; set; }
        public string OtherFinishDetails { get; set; }
        public string LaminatePreference { get; set; }
        public string DealerPOCText { get; set; }
        public bool NeedDWGFiles { get; set; }
        public bool NeedSP4Files { get; set; }
        public bool NeedSIFFiles { get; set; }
        public bool NeedXLSFiles { get; set; }
        public bool NeedPDFFiles { get; set; }
        public string GrommetPosition { get; set; }
        public string SpecTeamNotes { get; set; }
        public bool IsCanceled { get; set; }
        public string DealerPOCEmail { get; set; }
        public string DealerPOCPhone { get; set; }
        public Nullable<int> DealerPOCAcctType { get; set; }
        public string InternalNotes { get; set; }
        public bool IsOnHold { get; set; }
        public Nullable<int> ProjectID { get; set; }
        public string OldProjectName { get; set; }
        public string OldEndCustomer { get; set; }
        public Nullable<bool> OldIsGSA { get; set; }
        public Nullable<int> OldContractID { get; set; }
        public string VeneerPreference { get; set; }
    
        public virtual Company PrimaryCompany { get; set; }
        public virtual Company PaoliSalesRepGroup { get; set; }
        public virtual ICollection<SpecRequestFile> SpecRequestFiles { get; set; }
        public virtual User DealerSalesRep { get; set; }
        public virtual User SpecTeamMember { get; set; }
        public virtual ICollection<Typical> Typicals { get; set; }
        public virtual User PaoliSalesRepMember { get; set; }
        public virtual ICollection<SpecRequestEvent> SpecRequestEvents { get; set; }
        public virtual Project Project { get; set; }
    }
    
}
