//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace PDWDBContext
{
    public partial class TAttributeOption
    {
        public TAttributeOption()
        {
            this.TypicalOptionAttributes = new HashSet<TypicalOptionAttribute>();
        }
    
        public int OptionID { get; set; }
        public string Name { get; set; }
        public int AttributeID { get; set; }
    
        public virtual ICollection<TypicalOptionAttribute> TypicalOptionAttributes { get; set; }
        public virtual TAttribute TAttribute { get; set; }
    }
    
}
