//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace PDWDBContext
{
    public partial class TAttribute
    {
        public TAttribute()
        {
            this.TAttributeOptions = new HashSet<TAttributeOption>();
            this.TypicalIntAttributes = new HashSet<TypicalIntAttribute>();
            this.TypicalOptionAttributes = new HashSet<TypicalOptionAttribute>();
            this.TypicalTextAttributes = new HashSet<TypicalTextAttribute>();
        }
    
        public int AttributeID { get; set; }
        public string Name { get; set; }
        public bool DetailItem { get; set; }
    
        public virtual ICollection<TAttributeOption> TAttributeOptions { get; set; }
        public virtual ICollection<TypicalIntAttribute> TypicalIntAttributes { get; set; }
        public virtual ICollection<TypicalOptionAttribute> TypicalOptionAttributes { get; set; }
        public virtual ICollection<TypicalTextAttribute> TypicalTextAttributes { get; set; }
    }
    
}
