//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace PDWDBContext
{
    public partial class Territory
    {
        public Territory()
        {
            this.Companies = new HashSet<Company>();
            this.ZipCodeInfoes = new HashSet<ZipCodeInfo>();
        }
    
        public int TerritoryID { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<Company> Companies { get; set; }
        public virtual ICollection<ZipCodeInfo> ZipCodeInfoes { get; set; }
    }
    
}
