//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace PDWDBContext
{
    public partial class TerritoryTripData
    {
        public int CompanyID { get; set; }
        public int NewProductPoints { get; set; }
        public int FocusDealerPoints { get; set; }
        public int CurrentTerritoryVol { get; set; }
        public int TerritoryPoints { get; set; }
        public int NumDealerTripsAwarded { get; set; }
        public int DealerTripPoints { get; set; }
        public int EducationPoints { get; set; }
        public int TotalTripPoints { get; set; }
        public System.DateTime ImportDate { get; set; }
    
        public virtual Company Company { get; set; }
    }
    
}
