//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace PDWDBContext
{
    public partial class TypicalTextAttribute
    {
        public int ValueID { get; set; }
        public string Value { get; set; }
        public int AttributeID { get; set; }
        public int TypicalID { get; set; }
    
        public virtual TAttribute TAttribute { get; set; }
        public virtual Typical Typical { get; set; }
    }
    
}
