//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace PDWDBContext
{
    public partial class User
    {
        public User()
        {
            this.SpecRequests = new HashSet<SpecRequest>();
            this.SpecRequests1 = new HashSet<SpecRequest>();
            this.SpecRequests2 = new HashSet<SpecRequest>();
            this.CollateralOrders = new HashSet<CollateralOrder>();
            this.CollateralOrders1 = new HashSet<CollateralOrder>();
            this.CollateralOrders1_1 = new HashSet<CollateralOrder>();
            this.CollateralOrders_1 = new HashSet<CollateralOrder>();
            this.CollateralOrders_2 = new HashSet<CollateralOrder>();
            this.CollateralOrders5 = new HashSet<CollateralOrder>();
            this.CollateralOrders6 = new HashSet<CollateralOrder>();
            this.CollateralOrders7 = new HashSet<CollateralOrder>();
            this.CompaniesAsPaoliMember = new HashSet<Company>();
            this.CompaniesAsPaoliSalesRep = new HashSet<Company>();
            this.UserLogins = new HashSet<UserLogin>();
            this.ScoopArticles = new HashSet<ScoopArticle>();
            this.eCollateralItems = new HashSet<eCollateralItem>();
            this.eCollateralItems1 = new HashSet<eCollateralItem>();
            this.eCollateralItems2 = new HashSet<eCollateralItem>();
            this.SpecRequestEvents = new HashSet<SpecRequestEvent>();
            this.LeadTimeDetails = new HashSet<LeadTimeDetail>();
            this.Users1 = new HashSet<User>();
        }
    
        public int UserID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Zip { get; set; }
        public string Email { get; set; }
        public string BusinessPhone { get; set; }
        public string CellPhone { get; set; }
        public string Title { get; set; }
        public string Password { get; set; }
        public bool Enabled { get; set; }
        public int AccountType { get; set; }
        public int CompanyID { get; set; }
        public bool RecWelcomeEmail { get; set; }
        public string ImageFileName { get; set; }
        public bool IsTempPassword { get; set; }
        public bool IsActive { get; set; }
        public string AuthorCredit { get; set; }
        public int DefaultShippingAddress { get; set; }
        public bool ViewPerfData { get; set; }
        public string TierGroup { get; set; }
        public string HomeAddress1 { get; set; }
        public string HomeAddress2 { get; set; }
        public string HomeCity { get; set; }
        public string HomeState { get; set; }
        public string HomeZip { get; set; }
        public string HomePhone { get; set; }
        public string PersonalCellPhone { get; set; }
        public string FAX { get; set; }
        public string Extension { get; set; }
        public Nullable<int> CreatedByUser { get; set; }
        public Nullable<System.DateTime> CreatedDateTime { get; set; }
        public bool AllowNewsMgmt { get; set; }
    
        public virtual ICollection<SpecRequest> SpecRequests { get; set; }
        public virtual ICollection<SpecRequest> SpecRequests1 { get; set; }
        public virtual Company Company { get; set; }
        public virtual ICollection<SpecRequest> SpecRequests2 { get; set; }
        public virtual ICollection<CollateralOrder> CollateralOrders { get; set; }
        public virtual ICollection<CollateralOrder> CollateralOrders1 { get; set; }
        public virtual ICollection<CollateralOrder> CollateralOrders1_1 { get; set; }
        public virtual ICollection<CollateralOrder> CollateralOrders_1 { get; set; }
        public virtual ICollection<CollateralOrder> CollateralOrders_2 { get; set; }
        public virtual ICollection<CollateralOrder> CollateralOrders5 { get; set; }
        public virtual ICollection<CollateralOrder> CollateralOrders6 { get; set; }
        public virtual ICollection<CollateralOrder> CollateralOrders7 { get; set; }
        public virtual ICollection<Company> CompaniesAsPaoliMember { get; set; }
        public virtual ICollection<Company> CompaniesAsPaoliSalesRep { get; set; }
        public virtual ICollection<UserLogin> UserLogins { get; set; }
        public virtual ICollection<ScoopArticle> ScoopArticles { get; set; }
        public virtual ICollection<eCollateralItem> eCollateralItems { get; set; }
        public virtual ICollection<eCollateralItem> eCollateralItems1 { get; set; }
        public virtual ICollection<eCollateralItem> eCollateralItems2 { get; set; }
        public virtual ICollection<SpecRequestEvent> SpecRequestEvents { get; set; }
        public virtual ICollection<LeadTimeDetail> LeadTimeDetails { get; set; }
        public virtual UserNotification UserNotification { get; set; }
        public virtual ICollection<User> Users1 { get; set; }
        public virtual User User1 { get; set; }
    }
    
}
